### ISSUE TITLE
SpaceGoat Token Logo Question

### ISSUE THREAD

**Issue by spacegoat-dev** [trustwallet/assets#11561]
Hi there, 

Before we submitted another PR to you, I just wanted to confirm if we could get our logo on trust as now our price is showing due to our CoinMarketCap listing yesterday. Holder count - 1711

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
Closing PR for now. Please come back to us when all criteria are met.

**Comment by spacegoat-dev** [comment]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
> See the criteria at https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

I can see why you would need to increase those values. Now we have to work a little harder to hit the mark lol I will just have to tell the community to be patient for a little longer :) thank you for the help
