### ISSUE TITLE
Too big fee

### ISSUE THREAD

**Issue by Antonzlo** [trustwallet/assets#19804]
## How can we help ?

Why is the fee 700 TWT or 700+$? Servers do not cost this much, and Github actions are free. I am not against some fee, like 10 or 50$, but not 700$

**Comment by Lololololkhff** [comment]
```**

**Comment by getpaidceo** [comment]
> ## How can we help ?
> Why is the fee 700 TWT or 700+$? Servers do not cost this much, and Github actions are free. I am not against some fee, like 10 or 50$, but not 700$

Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
See also the PR Fee FAQ.

Please pay 300 TWT with the memo 107392805 to the address bnb136ns6lfw4zs5hg4n85vdthaad7hq5m4gtkgf23
Alternatively, 3 BNB is also accepted (same memo & address).

QR code: Trust | other wallet

Notes:

Trust Wallet Tokens (TWT) can be obtained through our Referral Program or from DEXs/exchanges.

New tokens without significant usage are rejected, see criteria mentioned above.

One PR should be for a single project; PR's with more than 10 logos will be rejected.

Payment evaluation happens automatically, but with a few minutes delay. When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.

Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.

TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

There will be a fee to process this request. None of it goes to the developers.
Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.

**Comment by getpaidceo** [comment]
Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
See also the PR Fee FAQ.

Please pay 300 TWT with the memo 107392805 to the address bnb136ns6lfw4zs5hg4n85vdthaad7hq5m4gtkgf23
Alternatively, 3 BNB is also accepted (same memo & address).

QR code: Trust | other wallet

Notes:

Trust Wallet Tokens (TWT) can be obtained through our Referral Program or from DEXs/exchanges.

New tokens without significant usage are rejected, see criteria mentioned above.

One PR should be for a single project; PR's with more than 10 logos will be rejected.

Payment evaluation happens automatically, but with a few minutes delay. When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.

Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.

TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

There will be a fee to process this request. None of it goes to the developers.
Before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
If you are paying TWT for the submission, this will be burned automatically. There will be no refunds.
