### ISSUE TITLE
[WIP] Improve Validation

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/assets#2694]
Mission: Assets repo to be the most comprehensive and up-to-date coin (sh@tcoin) repository available, used by several projects.

Identified Problems:
- CI run for a change is too slow (>4min; should check only diff)
- Code quality issues: hard to read, not well organized, constants in code, etc.
- Some automatic sanity fixes could be done in the PR builds (e.g. image resolution & compression, ETH contract format, json format).
- Regular generation of cumulative lists clutters git repo & history, requires build

Steps -- Phase 1:
- Speed up CI build, to check only diff
- Revisit operations performed in PR check and housekeeping builds
- Sanity fixes in PR build: ETH contract format
- Sanity fixes in PR build: image size (pixel, compression)

Steps - Phase 2:
- Code reorganization: more modular code
- Remove coinmarketcap info file
- Revisit execution logic of housekeeping build (schedule, triggered, minimum time between runs)
- Revisit usage of generated lists -- they can be generated wherever used; generation clutters git repo & history, requires build

Steps - Phase 3:
- Web app frontend (or GitHub App): Assist fork creation, PR creation; Image preparations; workflows for common use cases.

Common use cases:
- Add ERC20 token, logo (optional info)
- Add BEP2 token, logo

Common mistakes:
- Eth address not in checksum format
- Image file is too large (resolution or file size)
- Wrong filename/folder (not logo.png; contract.png instead of contract/logo.png)

**Comment by catenocrypt** [comment]
Reopen, updated description with issues/plan.

**Comment by catenocrypt** [comment]
Speed optimization: more efficient algo for black/whitelist; a speedup of about 30 sec (last times:  4:55 m vs. 3:31).

**Comment by catenocrypt** [comment]
Here is an update on the plan/progress:

- Speed up CI build, to check only diff

Checks have been speed up (check itself <10 sec, whole build <1min).
This speed means that checking only diffs would add code complexity withe very little improvement, so not planned any more

- Revisit operations performed in PR check and housekeeping builds -- **Done**

- Sanity fixes in PR build: ETH contract format
- Sanity fixes in PR build: image size (pixel, compression)

Auto-fixes are still not finalized, not really possible due to GitHub technicalities -- #3119 .
Steps - Phase 2:

- Code reorganization: more modular code -- **Done**

- Remove coinmarketcap info file -- not yet, later
    
- Revisit execution logic of housekeeping build (schedule, triggered, minimum time between runs) -- **Done**

- Revisit usage of generated lists -- they can be generated wherever used; generation clutters git repo & history, requires build 

Aggregated 'generated' lists have the advantage that they are available as a plain file from GH, no need for an API.  No change planned.

-- Web app frontend (or GitHub App): Assist fork creation, PR creation; Image preparations; workflows for common use cases. -- still planned

**Comment by catenocrypt** [comment]
Current updated build guideline.
Set of fixes is broken up into two: sanity fixes (must pass on PR) and consistency fixes.

1. On PR, sanity check is executed to verify the contribution changes: logo has correct naming and size, info.json is correct if present.  Passing check is precondition for merge (no work-around)
2. For sanity checks, automatic correction is done, checks in to source fork branch.  Notes:
 2.a. If fork does not allow Actions, auto check will not work
 2.b. If auto fix happens, resulting in a new commit on the PR, for techinical reasons this commit will not trigger CI run, and thus the PR will not be mergeable.  This requires a manual intervention (e.g. adding whitespace to new info.json, or to README), but it is still easier than manual intervention to do the actial fix (like resize).
3, The same sanity checks are also performed on master, right after merge.
4. A second set of consistency checks verify that whitelists are consistent, jsons are nice-formatted.  Consistency checks are performed on master on push.
5. Auto-fixes for consistency are performed automatically on master, and commited automatically (new 2nd commit on master, if needed)
6. Periodic updated from external sources (e.g. adding new Binance tokens, updating CMC mapping) happen independently from PRs, on a scedule (twice daily).
