### ISSUE TITLE
Create list of whitelisted/blacklisted tokens

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/assets#291]
We need to add a script that will run on each new added token.

and create list from assets folder, example: https://github.com/trustwallet/assets/tree/master/blockchains/binance/assets

`whitelist.json`
and 
`blacklist.json`
https://github.com/trustwallet/assets/blob/master/blockchains/binance/blacklist.json

It's very important that if you add a token into `blacklist.json` it should not be presented in the `whitelist.json` 

- asset name/ID should be presented in the correct checksum
 Example:
   - Ethereum: `0xE71c041dCEd39e1C4D9Ad6d7098440c9E7700BdF`
  -  Tron: `TKzGwf2BNmeQghYAK8Unn2tsqLjTKciSUQ` or `123321`
  - BNB : `SLV-986`

**Comment by erc20devteam** [comment]
Hi @vikmeup, I do have some questions, before the new listing process on old process the token logo, symbol, name will appear in 24 hours after get merged. But now a days after getting merged token logo, name, symbol not appearing on app. Any solution please! Our client is worried about this when they check we've submitted all related valid info but their token is not on TrustWallet. Can you please give a solution so that can follow your guidance.

Example >> https://github.com/trustwallet/assets/pull/427

Contract Address: 0x8f2fc2ab67d61d30eb3478a4f9396ab1ca90ba21
Total Supply : 100,000,000 XHQ
Token Name : Global Healthcare Token
Symbol : XHQ
Decimals : 8
